remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
title: Breadcrumbs
description: Experiments in digital forensics and artefact behaviour.
include:
  - assets/css/override.css
